version: '3'
networks:
  assignment-network:
    external: true
    name: 'mongo-network'

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGO_PASS: secret
      MONGO_HOST: mongodb
    networks:
      - assignment-network
    depends_on:
      - mongodb

  mongodb:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - assignment-network
    volumes:    
      - ./profiledata:/data/db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./profiledata:/data/db
    networks:
      - assignment-network


  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_DATABASE_ADMINUSERNAME=admin
      - ME_CONFIG_DATABASE_ADMINPASSWORD=secret
      - ME_CONFIG_DATABASE_SERVER=mongodb
    networks:
      - assignment-network
    depends_on:
      - mongodb

volumes:
  profiledata:
