version: '3'
networks:
  assignment-network:
    external: true
    name: 'mongo-network'

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGO_PASS: secret
      MONGO_HOST: mongodb
      MONGODB_URI: mongodb://admin:secret@mongodb:27017
      REDIS_URI: redis://mongodb
      ENABLE_WRITING_HANDLERS: = false
    networks:
      - assignment-network
    depends_on:
      - mongodb

  mongodb:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - assignment-network
    volumes:
      - ./mongodb-data:/data/db  # Changed volume name for mongodb

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data  # Changed volume name and target directory for Redis
    networks:
      - assignment-network

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin  # Corrected environment variable names
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - assignment-network
    depends_on:
      - mongodb

volumes:
  mongodb-data:
  redis-data:
