networks:
  redis-network:
    external: true
    name: 'mongo-network'
  mongodb-network:
    external: true
    name: 'mongo-network'
  api-network:
    external: true
    name: 'mongo-network'

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGO_PASS: secret
      MONGO_HOST: mongodb
      MONGODB_URI: mongodb://admin:secret@mongodb:27017
      REDIS_URI: redis://redis
      ENABLE_WRITING_HANDLERS: "false"  # Corrected value format
    networks:
      - mongodb-network
      - redis-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - mongodb-network
      - api-network
    volumes:
      - ./moviesData:/data/db

  seeding:
    image: mongo:8.0-rc
    container_name: seeding
    depends_on:
      - mongodb
    volumes:
      - ./seeding.json:/seed.json
    networks:
      - mongodb-network
    links:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    command:
      mongoimport --host mongodb --db tmdb_movies --collection movies --authenticationDatabase admin --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --drop --jsonArray --file /seed.json
    profiles:
      - dev


  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - api-network

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongodb-network
    # depends_on:
    #   - mongodb
    profiles:
      - dev

volumes:
  moviesData:
  redis-data:
